export const catBreeds = [
    { value: 'abyssinian', label: 'Abyssinian 阿比西尼亞貓' },
    { value: 'aegean', label: 'Aegean 愛琴海貓' },
    { value: 'american_bobtail', label: 'American Bobtail 美國短尾貓' },
    { value: 'american_curl', label: 'American Curl 美國捲耳貓' },
    { value: 'american_shorthair', label: 'American Shorthair 美國短毛貓' },
    { value: 'american_wirehair', label: 'American Wirehair 美國鋼毛貓' },
    { value: 'angora', label: 'Angora 安哥拉貓' },
    { value: 'arabian_mau', label: 'Arabian Mau 阿拉伯貓' },
    { value: 'asian_semi_longhair', label: 'Asian Semi-Longhair 亞洲半長毛貓' },
    { value: 'australian_mist', label: 'Australian Mist 澳大利亞迷霧貓' },
    { value: 'balinese', label: 'Balinese 峇里貓' },
    { value: 'bambino', label: 'Bambino 巴比諾貓' },
    { value: 'bengal', label: 'Bengal 豹貓' },
    { value: 'birman', label: 'Birman 伯曼貓' },
    { value: 'bombay', label: 'Bombay 孟買貓' },
    { value: 'british_longhair', label: 'British Longhair 英國長毛貓' },
    { value: 'british_shorthair', label: 'British Shorthair 英國短毛貓' },
    { value: 'burmese', label: 'Burmese 緬甸貓' },
    { value: 'burmilla', label: 'Burmilla 亞洲波米拉貓' },
    { value: 'california_spangled', label: 'California Spangled 加州閃亮貓' },
    { value: 'chartreux', label: 'Chartreux 沙特爾貓' },
    { value: 'chausie', label: 'Chausie 非洲獅子貓' },
    { value: 'cheetoh', label: 'Cheetoh 奇多貓' },
    { value: 'chinchilla', label: 'Chinchilla 金吉拉貓' },
    { value: 'chinchilla_persian', label: 'Chinchilla Persian 金吉拉波斯貓' },
    { value: 'colorpoint_shorthair', label: 'Colorpoint Shorthair 重點色短毛貓' },
    { value: 'cornish_rex', label: 'Cornish Rex 柯尼斯捲毛貓' },
    { value: 'cross_breed_cat_20220113', label: 'Cross Breed Cat 混血貓' },
    { value: 'cymric', label: 'Cymric 威爾斯貓' },
    { value: 'devon_rex', label: 'Devon Rex 得文捲毛貓' },
    { value: 'domestick_short_hair_dsh', label: 'Domestic Short Hair (DSH) 家貓 / 唐貓' },
    { value: 'donskoy', label: 'Donskoy 唐斯芬克斯貓' },
    { value: 'dragon_li', label: 'Dragon Li 狸花貓' },
    { value: 'dwelf', label: 'Dwelf 德沃夫貓' },
    { value: 'egyptian_mau', label: 'Egyptian Mau 埃及貓' },
    { value: 'english_fold', label: 'English Fold 英格蘭摺耳貓' },
    { value: 'european_burmese', label: 'European Burmese 歐洲緬甸貓' },
    { value: 'european_shorthair', label: 'European Shorthair 歐洲短毛貓' },
    { value: 'exotic_longhair', label: 'Exotic Longhair 異國長毛貓' },
    { value: 'exotic_shorthair', label: 'Exotic Shorthair 異國短毛貓' },
    { value: 'german_rex', label: 'German Rex 德國捲毛貓' },
    { value: 'havana_brown', label: 'Havana Brown 哈瓦那貓' },
    { value: 'highlander', label: 'Highlander 海蘭德貓' },
    { value: 'himalayan', label: 'Himalayan 喜馬拉亞貓' },
    { value: 'japanese_bobtail', label: 'Japanese Bobtail 日本短尾貓' },
    { value: 'javanese', label: 'Javanese 爪哇貓' },
    { value: 'khao_manee', label: 'Khao Manee 泰國御貓' },
    { value: 'korat', label: 'Korat 科拉特貓' },
    { value: 'laperm', label: 'LaPerm 法拉毛貓' },
    { value: 'maine_coon', label: 'Maine Coon 緬因貓' },
    { value: 'manx', label: 'Manx 曼島貓' },
    { value: 'mekong_bobtail', label: 'Mekong Bobtail 泰國短尾貓' },
    { value: 'minskin', label: 'Minskin 明斯克貓' },
    { value: 'mixed_breed_cat_20220113', label: 'Mixed Breed Cat 混種貓' },
    { value: 'munchkin', label: 'Munchkin 曼基貓' },
    { value: 'napoleon', label: 'Napoleon 拿破侖貓' },
    { value: 'nebelung', label: 'Nebelung 尼比隆貓' },
    { value: 'norwegian_forest_cat', label: 'Norwegian Forest Cat 挪威森林貓' },
    { value: 'ocicat', label: 'Ocicat 歐西貓' },
    { value: 'ojos_azules', label: 'Ojos Azules 歐斯亞史烈斯貓' },
    { value: 'oriental_longhair', label: 'Oriental Longhair 東方長毛貓' },
    { value: 'oriental_shorthair', label: 'Oriental Shorthair 東方短毛貓' },
    { value: 'peke_faced', label: 'Peke-Faced 獅子狗臉波斯貓' },
    { value: 'persian', label: 'Persian 波斯貓' },
    { value: 'peterbald', label: 'Peterbald 彼得禿貓' },
    { value: 'pixie_bob', label: 'Pixie-Bob 北美洲短毛貓' },
    { value: 'ragamuffin', label: 'Ragamuffin 襤褸貓' },
    { value: 'ragdoll', label: 'Ragdoll 布偶貓' },
    { value: 'russian_blue', label: 'Russian Blue 俄國藍貓' },
    { value: 'sam_sawet', label: 'Sam Sawet 暹羅貓' },
    { value: 'savannah', label: 'Savannah 熱帶草原貓' },
    { value: 'scottish_fold_coupari', label: 'Scottish Fold/Coupari 蘇格蘭摺耳貓' },
    { value: 'scottish_shorthair', label: 'Scottish Shorthair 蘇格蘭短毛貓' },
    { value: 'selkirk_rex', label: 'Selkirk Rex 塞扣克帝王貓' },
    { value: 'serengeti', label: 'Serengeti 塞倫蓋蒂貓' },
    { value: 'siamese', label: 'Siamese 暹邏貓' },
    { value: 'siberian', label: 'Siberian 西伯利亞貓' },
    { value: 'singapura', label: 'Singapura 新加坡貓' },
    { value: 'snowshoe', label: 'Snowshoe 雪鞋貓' },
    { value: 'sokoke', label: 'Sokoke 非洲短毛貓' },
    { value: 'somali', label: 'Somali 索馬利亞貓' },
    { value: 'sphynx_20220113', label: 'Sphynx 加拿大無毛貓' },
    { value: 'tabby_longhair', label: 'Tabby Longhair 長毛虎斑貓' },
    { value: 'tabby_shorthair', label: 'Tabby Shorthair 短毛虎斑貓' },
    { value: 'thai', label: 'Thai 泰國貓' },
    { value: 'tiffany_chantilly', label: 'Tiffany/Chantilly 查達利貓' },
    { value: 'tonkinese', label: 'Tonkinese 東奇尼貓' },
    { value: 'toyger', label: 'Toyger 玩具虎貓' },
    { value: 'turkish_angora', label: 'Turkish Angora 土耳其安哥拉貓' },
    { value: 'turkish_van', label: 'Turkish Van 土耳其凡城拉貓' },
    { value: 'ukrainian_levkoy', label: 'Ukrainian Levkoy 勒夫科伊貓' },
    { value: 'york_chocolate', label: 'York Chocolate 約克巧克力特貓' }
  ];
  
  export const dogBreeds = [
    { value: 'affenpinscher', label: 'Affenpinscher 猴㹴犬' },
    { value: 'afghan_hound', label: 'Afghan Hound 阿富汗獵犬' },
    { value: 'airedale_terrier', label: 'Airedale Terrier 萬能㹴犬' },
    { value: 'akita', label: 'Akita 秋田犬' },
    { value: 'alaskan_malamute_20220113', label: 'Alaskan Malamute 阿拉斯加雪橇犬' },
    { value: 'american_eskimo_dog', label: 'American Eskimo Dog 美國愛斯基摩犬' },
    { value: 'american_water_spaniel', label: 'American Water Spaniel 美國水獵犬' },
    { value: 'anatolian_shepherd_dog', label: 'Anatolian Shepherd Dog 安那托利亞牧羊犬' },
    { value: 'australian_cattle_dog', label: 'Australian Cattle Dog 澳洲牧牛犬' },
    { value: 'australian_shepherd', label: 'Australian Shepherd 澳洲牧羊犬' },
    { value: 'australian_silky_terrier', label: 'Australian Silky Terrier 絲毛梗犬' },
    { value: 'australian_terrier', label: 'Australian Terrier 澳大利亞㹴犬' },
    { value: 'azawakh', label: 'Azawakh 阿沙瓦犬' },
    { value: 'basenji', label: 'Basenji 巴辛吉犬' },
    { value: 'basset_bleu_de_gascogne', label: 'Basset Bleu De Gascogne 藍加斯科尼矮腿獵犬' },
    { value: 'basset_fauve_de_bretagne', label: 'Basset Fauve De Bretagne 布列塔尼短腿獵犬' },
    { value: 'basset_hound', label: 'Basset Hound 巴薩亨犬' },
    { value: 'bavarian_mountain_hound', label: 'Bavarian Mountain Hound 巴伐利亞山地犬' },
    { value: 'beagle', label: 'Beagle 比高犬' },
    { value: 'bearded_collie', label: 'Bearded Collie 古代長鬚牧羊犬' },
    { value: 'beauceron', label: 'Beauceron 法蘭西野狼犬' },
    { value: 'bedlington_terrier', label: 'Bedlington Terrier 貝林登犬' },
    { value: 'bergamasco', label: 'Bergamasco 貝加馬斯卡犬' },
    { value: 'bernese_mountain_dog', label: 'Bernese Mountain Dog 伯恩山犬' },
    { value: 'bichon_frise', label: 'Bichon Frise 比熊犬' },
    { value: 'black_and_tan_english_toy_terrier', label: 'Black And Tan English Toy Terrier 英國玩具梗犬' },
    { value: 'bloodhound', label: 'Bloodhound 尋血獵犬' },
    { value: 'bolognese', label: 'Bolognese 博洛尼亞犬' },
    { value: 'border_collie', label: 'Border Collie 邊界牧羊犬' },
    { value: 'border_terrier', label: 'Border Terrier 邊境梗犬' },
    { value: 'borzoi', label: 'Borzoi 波索犬' },
    { value: 'boston_terrier', label: 'Boston Terrier 波士頓爹利犬' },
    { value: 'bouvier_des_flandres', label: 'Bouvier Des Flandres 法蘭德斯牧羊犬' },
    { value: 'boxer', label: 'Boxer 拳師犬' },
    { value: 'bracco_italiano', label: 'Bracco Italiano 意大利布拉可犬' },
    { value: 'briard', label: 'Briard 伯瑞犬' },
    { value: 'brittany', label: 'Brittany 不列塔尼犬' },
    { value: 'bull_terrier_new', label: 'Bull Terrier 牛頭梗犬' },
    { value: 'bulldog', label: 'Bulldog 老虎犬' },
    { value: 'bullmastiff', label: 'Bullmastiff 鬥牛獒犬' },
    { value: 'cairn_terrier', label: 'Cairn Terrier 凱恩㹴犬' },
    { value: 'canaan_dog', label: 'Canaan Dog 迦南犬' },
    { value: 'catalan_sheepdog', label: 'Catalan Sheepdog 加泰羅尼亞牧羊犬' },
    { value: 'caucasian_shepherd_dog', label: 'Caucasian Shepherd Dog 高加索犬' },
    { value: 'cavalier_king_charles_spaniel', label: 'Cavalier King Charles Spaniel 騎士查理王獵犬' },
    { value: 'cesky_terrier', label: 'Cesky Terrier 捷克梗犬' },
    { value: 'chesapeake_bay_retriever', label: 'Chesapeake Bay Retriever 乞沙比克獵犬' },
    { value: 'chihuahua', label: 'Chihuahua 芝娃娃' },
    { value: 'chinese_crested_dog', label: 'Chinese Crested Dog 中國冠毛犬' },
    { value: 'chow_chow', label: 'Chow Chow 鬆獅犬' },
    { value: 'cirneco_dell_etna', label: 'Cirneco Dell\'etna 西西里獵犬' },
    { value: 'clumber_spaniel', label: 'Clumber Spaniel 克倫伯犬' },
    { value: 'cocker_spaniel', label: 'Cocker Spaniel 曲架犬' },
    { value: 'coton_de_tulear', label: 'Coton De Tulear 棉花面紗犬' },
    { value: 'cross_breed_dog_20220113', label: 'Cross Breed Dog 混血犬' },
    { value: 'curly_coated_retriever', label: 'Curly Coated Retriever 卷毛尋回犬' },
    { value: 'dachshund', label: 'Dachshund 臘腸犬' },
    { value: 'dalmatian', label: 'Dalmatian 大麥町犬' },
    { value: 'dandie_dinmont_terrier', label: 'Dandie Dinmont Terrier 丹迪丁蒙梗犬' },
    { value: 'deerhound', label: 'Deerhound 蘇格蘭獵鹿犬' },
    { value: 'dobermann', label: 'Dobermann 都柏文犬' },
    { value: 'dogue_de_bordeaux', label: 'Dogue De Bordeaux 波爾多犬' },
    { value: 'english_setter', label: 'English Setter 英國塞特犬' },
    { value: 'english_springer_spaniel', label: 'English Springer Spaniel 英國史賓格犬' },
    { value: 'estrela_mountain_dog', label: 'Estrela Mountain Dog 埃什特雷拉山犬' },
    { value: 'eurasier', label: 'Eurasier 歐亞犬' },
    { value: 'field_spaniel', label: 'Field Spaniel 田野獵犬' },
    { value: 'finnish_lapphund', label: 'Finnish Lapphund 芬蘭拉普獵犬' },
    { value: 'finnish_spitz', label: 'Finnish Spitz 芬蘭獵犬' },
    { value: 'flat_coated_retriever', label: 'Flat Coated Retriever 平毛尋回犬' },
    { value: 'fox_terrier', label: 'Fox Terrier 獵狐爹利犬' },
    { value: 'foxhound', label: 'Foxhound 英國獵狐犬' },
    { value: 'french_bulldog_20220113', label: 'French Bulldog 法國老虎犬' },
    { value: 'german_pinscher', label: 'German Pinscher 德國迷你品犬' },
    { value: 'german_shepherd_dog', label: 'German Shepherd Dog 德國牧羊犬' },
    { value: 'german_spitz', label: 'German Spitz 德國狐狸犬' },
    { value: 'glen_of_imaal_terrier', label: 'Glen Of Imaal Terrier 峽谷依馬爾梗犬' },
    { value: 'golden_retriever_20220113', label: 'Golden Retriever 金毛尋回犬' },
    { value: 'gordon_setter', label: 'Gordon Setter 哥頓塞特犬' },
    { value: 'grand_basset_griffon_vendeen', label: 'Grand Basset Griffon Vendeen 貝吉格裏芬凡丁犬' },
    { value: 'great_dane', label: 'Great Dane 大丹犬' },
    { value: 'greater_swiss_mountain_dog', label: 'Greater Swiss Mountain Dog 大瑞士山地犬' },
    { value: 'greenland_dog', label: 'Greenland Dog 格林蘭犬' },
    { value: 'greyhound', label: 'Greyhound 靈緹犬' },
    { value: 'griffon_bruxellois', label: 'Griffon Bruxellois 布魯塞爾格林芬犬' },
    { value: 'groenendael_belgian_shepherd_dog', label: 'Groenendael Belgian Shepherd Dog 比利時牧羊犬' },
    { value: 'hamiltonstovare', label: 'Hamiltonstovare 漢密爾頓獵犬' },
    { value: 'havanese', label: 'Havanese 哈威那犬' },
    { value: 'hovawart', label: 'Hovawart 霍夫瓦爾特犬' },
    { value: 'hungarian_kuvasz', label: 'Hungarian Kuvasz 哥威斯犬' },
    { value: 'hungarian_puli', label: 'Hungarian Puli 波利犬' },
    { value: 'hungarian_vizsla', label: 'Hungarian Vizsla 維茲拉犬' },
    { value: 'hungarian_wirehaired_vizsla', label: 'Hungarian Wirehaired Vizsla 剛毛維茲拉犬' },
    { value: 'ibizan_hound', label: 'Ibizan Hound 依比沙獵犬' },
    { value: 'irish_red_and_white_setter', label: 'Irish Red And White Setter 愛爾蘭紅白雪達犬' },
    { value: 'irish_setter', label: 'Irish Setter 愛爾蘭雪達犬' },
    { value: 'irish_terrier', label: 'Irish Terrier 愛爾蘭梗犬' },
    { value: 'irish_water_spaniel', label: 'Irish Water Spaniel 愛爾蘭水獵犬' },
    { value: 'irish_wolfhound', label: 'Irish Wolfhound 愛爾蘭獵狼犬' },
    { value: 'italian_greyhound', label: 'Italian Greyhound 意大利格雷伊獵犬' },
    { value: 'italian_spinone', label: 'Italian Spinone 史華諾犬' },
    { value: 'jack_russell_terrier', label: 'Jack Russell Terrier 積羅素犬' },
    { value: 'japanese_akita_inu', label: 'Japanese Akita Inu 日本秋田犬' },
    { value: 'japanese_chin', label: 'Japanese Chin 日本狆犬' },
    { value: 'japanese_shiba_inu', label: 'Japanese Shiba Inu 柴犬' },
    { value: 'japanese_spitz', label: 'Japanese Spitz 銀狐犬' },
    { value: 'keeshond', label: 'Keeshond 荷蘭毛獅犬' },
    { value: 'kerry_blue_terrier', label: 'Kerry Blue Terrier 凱利藍爹利犬' },
    { value: 'komondor', label: 'Komondor 可蒙犬' },
    { value: 'kooikerhondje', label: 'Kooikerhondje 科克爾犬' },
    { value: 'korean_jindo', label: 'Korean Jindo 韓國珍島犬' },
    { value: 'korthals_griffon', label: 'Korthals Griffon 科薩斯格裏芬犬' },
    { value: 'labrador_retriever_20220113', label: 'Labrador Retriever 拉布拉多尋回犬' },
    { value: 'laekenois_belgian_shepherd_dog', label: 'Laekenois Belgian Shepherd Dog 拉坎諾斯牧羊犬' },
    { value: 'lagotto_romagnolo', label: 'Lagotto Romagnolo 拉戈托羅馬閣挪露犬' },
    { value: 'lakeland_terrier', label: 'Lakeland Terrier 湖畔梗犬' },
    { value: 'lancashire_heeler', label: 'Lancashire Heeler 蘭開夏赫勒犬' },
    { value: 'leonberger', label: 'Leonberger 蘭伯格犬' },
    { value: 'lhasa_apso', label: 'Lhasa Apso 拉薩犬' },
    { value: 'lowchen', label: 'Lowchen 羅秦犬' },
    { value: 'malinois_belgian_shepherd_dog', label: 'Malinois Belgian Shepherd Dog 比利時馬連萊犬' },
    { value: 'maltese', label: 'Maltese 魔天使犬' },
    { value: 'manchester_terrier', label: 'Manchester Terrier 曼徹斯特梗犬' },
    { value: 'maremma_sheepdog', label: 'Maremma Sheepdog 馬瑞馬牧羊犬' },
    { value: 'mastiff', label: 'Mastiff 馬士提夫犬' },
    { value: 'mexican_hairless', label: 'Mexican Hairless 墨西哥無毛犬' },
    { value: 'miniature_pinscher', label: 'Miniature Pinscher 迷你品犬' },
    { value: 'miniature_poodle', label: 'Poodle 貴婦犬' },
    { value: 'mixed_breed_dog_20220113', label: 'Mixed Breed Dog / Mongrel 混種犬 / 唐狗' },
    { value: 'munsterlander', label: 'Munsterlander 明斯特蘭德犬' },
    { value: 'neapolitan_mastiff', label: 'Neapolitan Mastiff 那不勒斯獒犬' },
    { value: 'newfoundland', label: 'Newfoundland 紐芬蘭犬' },
    { value: 'norfolk_terrier', label: 'Norfolk Terrier 諾福克梗犬' },
    { value: 'norwegian_buhund', label: 'Norwegian Buhund 挪威牧羊犬' },
    { value: 'norwegian_elkhound', label: 'Norwegian Elkhound 挪威獵麋犬' },
    { value: 'norwich_terrier', label: 'Norwich Terrier 羅威士梗犬' },
    { value: 'nova_scotia_duck_tolling_retriever', label: 'Nova Scotia Duck Tolling Retriever 新斯科細亞誘鴨尋回犬' },
    { value: 'old_english_sheepdog', label: 'Old English Sheepdog 英國古代牧羊犬' },
    { value: 'otterhound', label: 'Otterhound 奧達獵犬' },
    { value: 'papillon', label: 'Papillon 蝴蝶犬' },
    { value: 'parson_russell_terrier', label: 'Parson Russell Terrier 柏森羅素梗犬' },
    { value: 'pekingese', label: 'Pekingese 北京犬' },
    { value: 'petit_basset_griffon_vendeen', label: 'Petit Basset Griffon Vendeen 迷你貝吉格里芬凡丁犬' },
    { value: 'pharaoh_hound', label: 'Pharaoh Hound 法老王獵犬' },
    { value: 'pointer', label: 'English Pointer 英國指示犬' },
    { value: 'polish_lowland_sheepdog', label: 'Polish Lowland Sheepdog 波蘭低地牧羊犬' },
    { value: 'pomeranian', label: 'Pomeranian 松鼠犬' },
    { value: 'portuguese_water_dog', label: 'Portuguese Water Dog 葡萄牙水犬' },
    { value: 'pug_20220113', label: 'Pug 八哥犬' },
    { value: 'pyrenean_mastiff', label: 'Pyrenean Mastiff 比利牛斯獒犬' },
    { value: 'pyrenean_mountain_dog', label: 'Pyrenean Mountain Dog 大白熊犬' },
    { value: 'pyrenean_sheepdog', label: 'Pyrenean Sheepdog 比利牛斯牧羊犬' },
    { value: 'rhodesian_ridgeback', label: 'Rhodesian Ridgeback 羅德西亞山脈犬' },
    { value: 'rottweiler', label: 'Rottweiler 洛威拿犬' },
    { value: 'rough_collie', label: 'Rough Collie 粗毛牧羊犬' },
    { value: 'russian_black_terrier', label: 'Russian Black Terrier 俄羅斯梗犬' },
    { value: 'saint_bernard', label: 'Saint Bernard 聖班納犬' },
    { value: 'saluki', label: 'Saluki 沙路奇獵犬' },
    { value: 'samoyed_20220113', label: 'Samoyed 薩摩耶犬' },
    { value: 'schipperke', label: 'Schipperke 舒柏奇犬' },
    { value: 'schnauzer', label: 'Schnauzer 史納莎犬' },
    { value: 'scottish_terrier', label: 'Scottish Terrier 蘇格蘭爹利犬' },
    { value: 'sealyham_terrier', label: 'Sealyham Terrier 西里漢犬' },
    { value: 'segugio_italiano', label: 'Segugio Italiano 意大利獵犬' },
    { value: 'shar_pei', label: 'Shar Pei 沙皮犬' },
    { value: 'shetland_sheepdog', label: 'Shetland Sheepdog 小型牧羊犬' },
    { value: 'shih_tzu', label: 'Shih Tzu 西施犬' },
    { value: 'siberian_husky', label: 'Siberian Husky 西伯利亞雪橇犬' },
    { value: 'skye_terrier', label: 'Skye Terrier 斯凱島梗犬' },
    { value: 'sloughi', label: 'Sloughi 北非獵犬' },
    { value: 'smooth_collie', label: 'Smooth Collie 短毛牧羊犬' },
    { value: 'soft_coated_wheaten_terrier', label: 'Soft Coated Wheaten Terrier 愛爾蘭軟毛梗犬' },
    { value: 'spanish_water_dog', label: 'Spanish Water Dog 西班牙水犬' },
    { value: 'stafforshire_bull_terrier', label: 'Stafforshire Bull Terrier 史特富郡鬥牛梗犬' },
    { value: 'sussex_spaniel', label: 'Sussex Spaniel 塞式獵犬' },
    { value: 'swedish_lapphund', label: 'Swedish Lapphund 瑞典拉普獵犬' },
    { value: 'swedish_vallhund', label: 'Swedish Vallhund 瑞典瓦漢德犬' },
    { value: 'tervueren_belgian_shepherd_dog', label: 'Tervueren Belgian Shepherd Dog 比利時坦比連犬' },
    { value: 'tibetan_mastiff', label: 'Tibetan Mastiff 藏獒犬' },
    { value: 'tibetan_spaniel', label: 'Tibetan Spaniel 西藏獵犬' },
    { value: 'tibetan_terrier', label: 'Tibetan Terrier 西藏㹴犬' },
    { value: 'warren_hound_portuguese_podengo', label: 'Warren Hound Portuguese Podengo 葡萄牙波登可犬' },
    { value: 'weimaraner', label: 'Weimaraner 威瑪犬' },
    { value: 'welsh_corgi', label: 'Welsh Corgi 哥基犬' },
    { value: 'welsh_springer_spaniel', label: 'Welsh Springer Spaniel 威爾斯史賓格獵犬' },
    { value: 'welsh_terrier', label: 'Welsh Terrier 威爾斯㹴犬' },
    { value: 'west_highland_white_terrier', label: 'West Highland White Terrier 西部高地白爹利犬' },
    { value: 'whippet', label: 'Whippet 惠比特犬' },
    { value: 'yorkshire_terrier', label: 'Yorkshire Terrier 約瑟爹利犬' }
];

  export const petage = [
    { value: 'lt3m', label: '13週以下' },
    { value: '13w11m', label: '13週至11個月' },
    { value: '1y', label: '1歲' },
    { value: '2y', label: '2歲' },
    { value: '3y', label: '3歲' },
    { value: '4y', label: '4歲' },
    { value: '5y', label: '5歲' },
    { value: '6y', label: '6歲' },
    { value: '7y', label: '7歲' },
    { value: '8y', label: '8歲' },
    { value: '9y', label: '9歲' },
    { value: '10y', label: '10歲' },
    { value: '11y', label: '11歲' },
    { value: '12y', label: '12歲' },
    { value: '13y', label: '13歲' },
    { value: '14y', label: '14歲' },
    { value: 'me15y', label: '15歲或以上' },
  ];


// 香港 18 區列表
export const hongKongDistricts = [
  { value: '', label: '全部地區' },
  { value: 'Central and Western', label: '中西區' },
  { value: 'Eastern', label: '東區' },
  { value: 'Southern', label: '南區' },
  { value: 'Wan Chai', label: '灣仔區' },
  { value: 'Sham Shui Po', label: '深水埗區' },
  { value: 'Kowloon City', label: '九龍城區' },
  { value: 'Kwun Tong', label: '觀塘區' },
  { value: 'Wong Tai Sin', label: '黃大仙區' },
  { value: 'Yau Tsim Mong', label: '油尖旺區' },
  { value: 'Islands', label: '離島區' },
  { value: 'Kwai Tsing', label: '葵青區' },
  { value: 'North', label: '北區' },
  { value: 'Sai Kung', label: '西貢區' },
  { value: 'Sha Tin', label: '沙田區' },
  { value: 'Tai Po', label: '大埔區' },
  { value: 'Tsuen Wan', label: '荃灣區' },
  { value: 'Tuen Mun', label: '屯門區' },
  { value: 'Yuen Long', label: '元朗區' },
];
